blueprint:
  name: Control PV Limit to avoid exporting to the grid
  description: >
    # Zero Feed In Automation
    **Version: 0.0.7**

    # Summary
    This automation reacts to changes in energy imported from or exported to the grid.
    It dynamically sets the photovoltaic (PV) inverter power limit so that no
    (or only a user‑defined minimum) power is fed back to the grid.

    ## New in 0.0.7
    * **Percentage output** – The value written to *NonPersistantLimit* is now a **percentage** of the inverter’s maximum AC power instead of watts.
      It is calculated as `(new_setpoint / upperlimit) * 100` and rounded to the nearest whole percent.

    ## Required sensors / entities

    * **GridPowerMeters** – Sensors measuring grid import/export (e.g. L1, L2, L3) in W.
    * **BatteryPowerMeters** – *Optional*: Sensors measuring battery charge/discharge in W.
    * **PVPowerMeters** – Sensors measuring PV generation in W.
    * **NonPersistantLimit** – *Number* entity that stores the **percentage** power limit (0‑100 %).
    * **InverterOnlineStatus** – Binary/Text entity that is *"On"* or numeric *4* when the inverter is reachable.

    Kudos for the simple algorithm and idea go to:
    https://selbstbau-pv.de/wissensbasis/nulleinspeisung-hoymiles-hm-1500-mit-opendtu-python-steuerung/

    # Change log
    Full details: https://github.com/AndreBott83/HA_Zero_PV_Grid_Feed_in
  domain: automation
  input:
    TriggerInterval:
      name: Interval trigger
      description: Interval (seconds) between evaluations.
      default: 15
      selector:
        number:
          min: 5
          max: 120
          unit_of_measurement: "s"
          step: 5
    MaxInverterPower:
      name: Inverter upper limit (W)
      description: Maximum AC power the inverter can deliver.
      default: 1600
      selector:
        number:
          min: 0
          max: 5000
          unit_of_measurement: "W"
          mode: box
          step: 1
    MinInverterPower:
      name: Inverter lower limit (W)
      description: Minimum AC power the inverter should deliver.
      default: 600
      selector:
        number:
          min: 0
          max: 5000
          unit_of_measurement: "W"
          mode: box
          step: 1
    AllowedFeedIn:
      name: Allowed grid feed‑in (W)
      description: PV power reduction starts only if export exceeds this value.
      default: 0
      selector:
        number:
          min: 0
          max: 5000
          unit_of_measurement: "W"
          mode: box
          step: 1
    ModeSelector:
      name: Control mode selector
      description: "1 → smooth control, 2 → hard cut to zero feed‑in."
      default: 1
      selector:
        number:
          min: 1
          max: 2
          step: 1
    InvertGrid:
      name: Invert GridPowerMeters?
      description: Enable if your GridPowerMeters report export as positive.
      default: false
      selector:
        boolean:
    GridPowerMeters:
      name: Grid power sensors (W)
      description: e.g. all three phase sensors L1, L2, L3.
      selector:
        entity:
          device_class: power
          multiple: true
    BatteryPowerMeters:
      name: Battery power sensors (optional)
      description: Sensors reporting battery charge/discharge power (positive for discharge).
      default: []
      selector:
        entity:
          device_class: power
          multiple: true
    PVPowerMeters:
      name: PV generation sensors (W)
      description: Sensors measuring current PV power.
      selector:
        entity:
          device_class: power
          multiple: true
    NonPersistantLimit:
      name: Non‑persistent PV limit entity (%)
      description: Number entity to write the calculated PV limit percentage (0‑100).
      selector:
        entity:
    InverterOnlineStatus:
      name: Inverter online status
      description: Entity that indicates the inverter is reachable ("On" or 4).
      selector:
        entity:

variables:
  triggerinterval: !input "TriggerInterval"
  lowerlimit: !input "MinInverterPower"
  upperlimit: !input "MaxInverterPower"
  currentlimit: !input "NonPersistantLimit"
  PVPowerMetersvar: !input "PVPowerMeters"
  GridPowerMetersvar: !input "GridPowerMeters"
  BatteryPowerMetersvar: !input "BatteryPowerMeters"
  ctlr_mode: !input "ModeSelector"
  invert_grid: !input "InvertGrid"
  pvgeneration: >
    {% set pv = expand(PVPowerMetersvar) | map(attribute='state') | map('float', default=0) | sum %}
    {{ pv }}
  grid_raw: >
    {% set grid = expand(GridPowerMetersvar) | map(attribute='state') | map('float', default=0) | sum %}
    {% if invert_grid %}
      {% set grid = grid * -1 %}
    {% endif %}
    {{ grid }}
  battery_raw: >
    {% set bat = expand(BatteryPowerMetersvar) | map(attribute='state') | map('float', default=0) | sum %}
    {{ bat }}
  gridsum: >
    {{ grid_raw + battery_raw }}
  modifier: !input "AllowedFeedIn"
  modifier_setpoint: >
    {% if gridsum | float(0) < 0 %}
      {{ modifier }}
    {% else %}
      100
    {% endif %}
  inverteronline: !input "InverterOnlineStatus"
  new_setpoint_mode1: >
    {% set setpoint = gridsum | float(0) + modifier_setpoint | float(0) + states(currentlimit) | float(0) - 5 %}
    {% if setpoint > upperlimit %}
      {% set setpoint = upperlimit %}
    {% elif setpoint < lowerlimit %}
      {% set setpoint = lowerlimit %}
    {% endif %}
    {{ setpoint }}
  new_setpoint_mode2: >
    {% set setpoint = gridsum | float(0) + modifier_setpoint | float(0) + pvgeneration | float(0) + 5 %}
    {% if setpoint > upperlimit %}
      {% set setpoint = upperlimit %}
    {% elif setpoint < lowerlimit %}
      {% set setpoint = lowerlimit %}
    {% endif %}
    {{ setpoint }}
  new_setpoint: >
    {% if ctlr_mode == 1 %}
      {{ new_setpoint_mode1 | round(0) }}
    {% elif ctlr_mode == 2 %}
      {{ new_setpoint_mode2 | round(0) }}
    {% endif %} 
  percent_setpoint: >
    {% if upperlimit | float(0) > 0 %}
      {{ (new_setpoint | float(0) / upperlimit | float(0)) * 100 | round(0) }}
    {% else %}
      100
    {% endif %}

trigger:
  - platform: state
    entity_id: !input "GridPowerMeters"

condition:
  - condition: template
    value_template: "{{ states(inverteronline) == '4' }}"
  - condition: template
    value_template: |
      {% set last = state_attr(this.entity_id, 'last_triggered') %}
      {{ last is none or (last is not none and (now() - last) > timedelta(seconds=triggerinterval)) }}
  - condition: template
    value_template: "{{ (percent_setpoint - states(currentlimit) | float(0)) | abs > 1 }}"

action:
  - service: logbook.log
    data_template:
      name: "PVSetpoint%:"
      message: "Gridsum: {{ gridsum }} W (Grid: {{ grid_raw }} W + Battery: {{ battery_raw }} W) & PVGeneration: {{ pvgeneration }} W -> new_setpoint: {{ new_setpoint }} W ({{ percent_setpoint }} %)"
  - service: number.set_value
    target:
      entity_id: !input "NonPersistantLimit"
    data:
      value: "{{ percent_setpoint }}"

mode: single

